### ISSUE TITLE
How to backup and restore DAF data

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf#202] opened 2020-06-12 09:32 UTC
When using DAF on a mobile app, we need the user to be able to restore his claims and attestations, if he changes or even lost his mobile. So, how to backup and restore the user data? And if you currently do not provide an API call to get the user data as one file and then restore from that file, do you plan to provide this functionality in the future?

And do you have any recommendations for encryption and where to save the user data?

Many Thanks,

**Comment by mirceanis** [comment] 2020-08-26 14:13
DAF does not provide this functionality out of the box, and probably won't provide it in the future.
This is because there can be different storage plugins that can be used, and they can be used selectively depending on the configuration of the agent, and the platform where DAF is being used.
This also means that there will be specific backup options for each plugin.

This, of course, covers the entire database behind an agent running DAF.
When it comes to backup of a single user's data, the story gets more complicated, because it depends on the kind of app where DAF is used, whether all the user data is in one place or distributed between multiple systems, etc..
Besides the location of the backed up data, there is also the question of regaining access to it.

One potential solution is to use a mnemonic phrase as the generator of user keys.
Some of these keys will be used for generating DIDs, some for signing, some for encryption.
If user data is encrypted in the backup system using a key generated by this method, then the user can regain access to it if they reuse the mnemonic phrase.

At uPort we've used x25519 keys derived from a [bip39 mnemonic](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) to encrypt user events and back them up to a [blind storage system](https://github.com/uport-project/lambda-caleuche).
This is not in DAF core as it requires running some infrastructure.

I'm closing this, please reopen if the answer relating to DAF does not suffice.

**Closed by mirceanis** 2020-08-26 14:13 UTC

**Comment by Muhammad-Altabba** [comment] 2020-08-27 05:02
Thanks Mircea for your detailed answer.

Regarding what and how to backup for a specific user, what about backing his private keys (used for his/here identities) + all the JWTs he/she has. Would not this be enough and fully abstracted from the underlying storage used? And when restoring, we can recover his Identities from the private keys and by parsing all the JWTs that early stored. Is there any issues with this proposed solution?

Thanks,

**Comment by mirceanis** [comment] 2020-08-27 10:42
Of course, that would work. Technically, that is all the user data.
However, during restoration of the data, special precaution must be taken by the app:

1. Keys need to be restored before other data. Mostly because some keys may be used to decrypt some of the incoming data.

2. The app needs to avoid triggering the actions that may be embedded in the various messages and JWTs being restored (some of the messages/JWTs/credentials can represent _signed selective disclosure requests_, for example)

3. There may also need to be special considerations for expired or revoked credentials.
JWTs/Credentials can be invalid for being expired, for being signed by an unknown key and for being revoked.
The revocation check is voluntary, so DAF does not perform it by default.
Credentials are also considered invalid if the keys that signed them are no longer listed in the DID document of the issuer.

Depending on how your app is structured, it may make sense to go with the defaults and let the invalid credentials be dropped. But if you have special logic that requires older or revoked credentials to be kept, extra work is necessary.


---

That being said, there are some implications that this sort of backup/restore mechanism has.

* If the new DID agent uses different service endpoints, the DID documents of the user need to be updated to reflect the new location(s).

* If the restore is being performed on a new agent while the old agent is still active, there may be issues caused by this duplication (missed messages, conflicting DID operations, loss of trust because of missing credentials/messages). Most of the time these are corner cases, but for very active agents, this becomes likely.
Synchronization between agents controlling the same keys is not provided by DAF out of the box.

* If the restoration is part of a migration of user data, there is the question of ensuring that the keys and data are destroyed on the origin. Otherwise, the user has no assurance that they are the sole controller of their keys.
