### ISSUE TITLE
intrinsic gas too low while creating identity service

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [uport-project/daf#255] opened 2020-10-26 09:01 UTC
i am trying to create identity service by using **identityManagerAddService** using **did:ethr:rinkeby DID**, but get the following error

`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32000,"message":"intrinsic gas too low"}}'`

**Comment by simonas-notcat** [comment] 2020-10-26 09:29
You can configure gas for the identity provider:

https://github.com/uport-project/daf/blob/beta/__tests__/localAgent.test.ts#L109

or pass gas value as part of method arguments:

https://github.com/uport-project/daf/blob/beta/docs/api/daf-core.iidentitymanageraddserviceargs.md

```
await agent.identityManagerAddService({
  did: ...,
  service: ...,
  options: {
     gas: ...
  }
})
```

**Comment by HamzaBinSarfraz** [comment] 2020-10-26 23:05
Thanks the **gas** issue is resolved but unfortunatly i am getting this error while creating identity service 

```

/home/ameer/.nvm/versions/node/v10.16.3/bin/node ./server.js
***************************************************************
 server.js
null: Error: Expected type object but found type string; identityManagerAddService; #/; INVALID_TYPE; undefined
    at new PluginReturnTypeError (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/src/validator.ts:33:5)
    at Object.exports.validateReturnType (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/src/validator.ts:56:11)
    at Agent.<anonymous> (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/src/agent.ts:198:7)
    at step (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/agent.js:44:23)
    at Object.next (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/agent.js:25:53)
    at fulfilled (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/agent.js:16:58) {name: 'PluginReturnTypeError', method: 'identityManagerAddService', description: undefined, path: '#/', code: 'INVALID_TYPE', …}
code: 'INVALID_TYPE'
description: undefined
message: 'Expected type object but found type string; identityManagerAddService; #/; INVALID_TYPE; undefined'
method: 'identityManagerAddService'
name: 'PluginReturnTypeError'
path: '#/'
stack: 'PluginReturnTypeError: Expected type object but found type string; identityManagerAddService; #/; INVALID_TYPE; undefined\n    at new PluginReturnTypeError (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/validator.js:41:28)\n    at Object.exports.validateReturnType (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/validator.js:65:15)\n    at Agent.<anonymous> (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/agent.js:233:41)\n    at step (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/agent.js:44:23)\n    at Object.next (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/agent.js:25:53)\n    at fulfilled (/home/ameer/hamza/git/daf7-demo/node_modules/daf-core/build/agent.js:16:58)'
__proto__: Error

```

Also my requested service looks like this 

```
const result = await agent.identityManagerAddService({
            did: did,
            service: {
                id: did,
                type: 'identityManagerImportIdentity',
                serviceEndpoint: 'http://localhost:3001/agent',
            },
            options: {
                gas: 1000001
            },
        });
```

**Comment by mirceanis** [comment] 2020-11-04 12:58
This looks like it's being caused by the schema validation on the return type of the `identityManagerAddService`.
It's likely that I'm wrong but from the looks of it, the call to `identityManagerAddService()` is returning `undefined`.

@simonas-notcat can you suggest a way to disable the schema check here so that the issue can be further debugged?

**Comment by mirceanis** [comment] 2020-11-23 17:57
@HamzaBinSarfraz can you try again using version [7.0.0-beta.47] and see if you make progress?

**Comment by mirceanis** [comment] 2020-11-24 16:47
Closing this since there is a workaround for the second issue as well. ( see #275 #278 #280 )

Thank you for reporting this.

**Closed by mirceanis** 2020-11-24 16:47 UTC
Labels: bug

**Comment by HamzaBinSarfraz** [comment] 2020-11-25 15:46
Yeah this issue is resolved, thanks @mirceanis @simonas-notcat
